### PR TITLE
Db models

### PR DESCRIPTION
**Pull request by NicholasGoh**

### CODE REVIEW

**Review by majulahsingapuri — APPROVED** [review]
Made some changes on your behalf. Note that SQLAlchemy defaults to setting columns as nullable. We need to manually set it to False to ensure data integrity

**Review by timothytancy — COMMENTED** [review]
super cool stuff, thanks nic!!!

**Comment by majulahsingapuri** [comment]
@NicholasGoh just to double confirm. the force push was just for pydantic?

**Comment by NicholasGoh** [comment]
@majulahsingapuri the force push was to test ssh key

**Pull request merged**
